<?php
/**
 * Template has been overwritten in order to:
 * 1. Implement PRG (Post-Redirect-Get) for facet navigation links masking
 * NOTE: This file is a copy of: 
 * `vendor/magento/module-swatches/view/frontend/templates/product/layered/renderer.phtml`
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Swatches\Block\LayeredNavigation\RenderLayered */
?>
<?php 
$swatchData = $block->getSwatchData();
// Post-Redirect-Get
$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
$isLinkMaskingEnabled = $swatchData['is_link_masking_enabled'];
$linkmaskingUrl = $this->getUrl('linkmasking/filter/redirect');
?>

<div class="swatch-attribute swatch-layered <?= /* @escapeNotVerified */ $swatchData['attribute_code'] ?>"
     attribute-code="<?= /* @escapeNotVerified */ $swatchData['attribute_code'] ?>"
     attribute-id="<?= /* @escapeNotVerified */ $swatchData['attribute_id'] ?>">
    <div class="swatch-attribute-options clearfix">
        <?php foreach ($swatchData['options'] as $option => $label): ?>
            <?php
                if (empty($option)) {
                    continue;
                }
                $swatchItemUrl = $label['link'];
                $swatchItemHref = $isLinkMaskingEnabled ? '#' : $swatchItemUrl;
            ?>
            <a href="<?= /* @escapeNotVerified */ $swatchItemHref; ?>"
               aria-label="<?= /* @escapeNotVerified */ $label['label'] ?>"
               <?php if($isLinkMaskingEnabled): ?>
                    data-post='<?= $postDataHelper->getPostData($linkmaskingUrl, ['url' => $swatchItemUrl]); ?>'
                <?php endif; ?>
               class="swatch-option-link-layered">
                <?php if (isset($swatchData['swatches'][$option]['type'])): ?>
                    <?php switch ($swatchData['swatches'][$option]['type']) {
                        case '3':
                            ?>
                            <div class="swatch-option <?= /* @escapeNotVerified */ $label['custom_style'] ?>"
                                 tabindex="-1"
                                 option-type="3"
                                 option-id="<?= /* @escapeNotVerified */ $option ?>"
                                 option-label="<?= /* @escapeNotVerified */ $label['label'] ?>"
                                 option-tooltip-thumb=""
                                 option-tooltip-value=""
                                ></div>
                            <?php    break;
                        case '2':
                            ?>
                            <?php $swatchThumbPath = $block->getSwatchPath('swatch_thumb', $swatchData['swatches'][$option]['value']); ?>
                            <?php $swatchImagePath = $block->getSwatchPath('swatch_image', $swatchData['swatches'][$option]['value']); ?>
                            <div class="swatch-option image <?= /* @escapeNotVerified */ $label['custom_style'] ?>"
                                 tabindex="-1"
                                 option-type="2"
                                 option-id="<?= /* @escapeNotVerified */ $option ?>"
                                 option-label="<?= /* @escapeNotVerified */ $label['label'] ?>"
                                 option-tooltip-thumb="<?= /* @escapeNotVerified */ $swatchThumbPath ?>"
                                 option-tooltip-value=""
                                 style="background: url(<?= /* @escapeNotVerified */ $swatchImagePath ?>) no-repeat center; background-size: initial;"></div>
                            <?php    break;
                        case '1':
                            ?>
                            <div class="swatch-option color <?= /* @escapeNotVerified */ $label['custom_style'] ?>"
                                 tabindex="-1"
                                 option-type="1"
                                 option-id="<?= /* @escapeNotVerified */ $option ?>"
                                 option-label="<?= /* @escapeNotVerified */ $label['label'] ?>"
                                 option-tooltip-thumb=""
                                 option-tooltip-value="<?= /* @escapeNotVerified */ $swatchData['swatches'][$option]['value'] ?>"
                                 style="background: <?= /* @escapeNotVerified */ $swatchData['swatches'][$option]['value'] ?> no-repeat center; background-size: initial;"></div>
                            <?php    break;
                        case '0':
                        default:
                            ?>
                                <div class="swatch-option text <?= /* @escapeNotVerified */ $label['custom_style'] ?>"
                                     tabindex="-1"
                                     option-type="0"
                                     option-id="<?= /* @escapeNotVerified */ $option ?>"
                                     option-label="<?= /* @escapeNotVerified */ $label['label'] ?>"
                                     option-tooltip-thumb=""
                                     option-tooltip-value=""
                                    ><?= /* @escapeNotVerified */ $swatchData['swatches'][$option]['value'] ?></div>
                            <?php    break;
                    } ?>
                <?php endif; ?>
            </a>
        <?php endforeach; ?>
    </div>
</div>

<script>
    require(["jquery", "Magento_Swatches/js/swatch-renderer"], function ($) {
        $('.swatch-layered.<?= /* @escapeNotVerified */ $swatchData['attribute_code'] ?>')
            .find('[option-type="1"], [option-type="2"], [option-type="0"], [option-type="3"]')
            .SwatchRendererTooltip();
    });
</script>
