<?php
/**
 * Template has been overwritten in order to:
 * 1. Implement PRG (Post-Redirect-Get) for facet navigation links masking
 * NOTE: This file is a copy of:
 * `vendor/creativestyle/magesuite-server-sider-swatches/view/frontend/templates/product/layered/renderer.phtml`
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Swatches\Block\LayeredNavigation\RenderLayered */
?>
<?php
$swatchData = $block->getSwatchData();
// Post-Redirect-Get
$postDataHelper = $this->helper(\Magento\Framework\Data\Helper\PostHelper::class);
/** @var \MageSuite\SeoLinkMasking\ViewModel\LayeredNavigation\RenderLayered $viewModel */
$viewModel = $block->getViewModel();
$isLinkMaskingEnabled = $swatchData['is_link_masking_enabled'];
$linkmaskingUrl = $this->getUrl('linkmasking/filter/redirect');
?>

<div class="swatch-attribute swatch-layered <?= $block->escapeHtmlAttr($swatchData['attribute_code']) ?>"
     attribute-code="<?= $block->escapeHtmlAttr($swatchData['attribute_code']) ?>"
     attribute-id="<?= $block->escapeHtmlAttr($swatchData['attribute_id']) ?>">
    <div class="swatch-attribute-options clearfix">
        <?php foreach ($swatchData['options'] as $option => $label) :?>
            <?php
                if (empty($option)) {
                    continue;
                }
                $swatchItemUrl = $label['link'];
                $swatchItemHref = $isLinkMaskingEnabled ? '#' : $swatchItemUrl;
                $swatchOption = $swatchData['swatches'][$option];
            ?>
            <a href="<?= $block->escapeUrl($swatchItemHref) ?>"
               aria-label="<?= $block->escapeHtmlAttr($label['label']) ?>"
               <?php if($isLinkMaskingEnabled): ?>
                    data-post='<?= $postDataHelper->getPostData($linkmaskingUrl, ['url' => $swatchItemUrl]); ?>'
                <?php endif; ?>
               class="swatch-option-link-layered">
                <?php if (isset($swatchOption['type'])) :?>
                    <?php switch ($swatchOption['type']) {
                        case '3':
                            ?>
                            <div class="swatch-option <?= $block->escapeHtmlAttr($label['custom_style']) ?>"
                                option-type="3"
                                data-option-type="3"
                                option-id="<?= $block->escapeHtmlAttr($option) ?>"
                                data-option-id="<?= $block->escapeHtmlAttr($option) ?>"
                                option-label="<?= $block->escapeHtmlAttr($label['label']) ?>"
                                data-option-label="<?= $block->escapeHtmlAttr($label['label']) ?>"
                                option-tooltip-thumb=""
                                data-option-tooltip-thumb=""
                                option-tooltip-value=""
                                data-option-tooltip-value="">
                            </div>
                            <?php break;
                        case '2':
                            ?>
                            <?php $swatchThumbPath = $block->getSwatchPath(
                                'swatch_thumb',
                                $swatchOption['value']
                            ); ?>
                            <?php $swatchImagePath = $block->getSwatchPath(
                                'swatch_image',
                                $swatchOption['value']
                            );
                            $escapedUrl = $block->escapeUrl($swatchImagePath);
                            ?>
                            <div class="swatch-option image <?= $block->escapeHtmlAttr($label['custom_style']) ?>"
                                option-type="2"
                                data-option-type="2"
                                option-id="<?= $block->escapeHtmlAttr($option) ?>"
                                data-option-id="<?= $block->escapeHtmlAttr($option) ?>"
                                option-label="<?= $block->escapeHtmlAttr($label['label']) ?>"
                                data-option-label="<?= $block->escapeHtmlAttr($label['label']) ?>"
                                option-tooltip-thumb="<?= $block->escapeUrl($swatchThumbPath) ?>"
                                data-option-tooltip-thumb="<?= $block->escapeUrl($swatchThumbPath) ?>"
                                option-tooltip-value=""
                                data-option-tooltip-value=""
                                style="background: url(<?= /*  @noEscape */ $escapedUrl ?>) no-repeat center; background-size: initial;">
                            </div>
                            <?php break;
                        case '1':
                            ?>
                            <div class="swatch-option color <?= $block->escapeHtmlAttr($label['custom_style']) ?>"
                                option-type="1"
                                data-option-type="1"
                                option-id="<?= $block->escapeHtmlAttr($option) ?>"
                                data-option-id="<?= $block->escapeHtmlAttr($option) ?>"
                                option-label="<?= $block->escapeHtmlAttr($label['label']) ?>"
                                data-option-label="<?= $block->escapeHtmlAttr($label['label']) ?>"
                                option-tooltip-thumb=""
                                data-option-tooltip-thumb=""
                                option-tooltip-value="<?= $block->escapeHtmlAttr($swatchOption['value']) ?>"
                                data-option-tooltip-value="<?= $block->escapeHtmlAttr($swatchOption['value']) ?>"
                                style="background: <?= $block->escapeHtmlAttr($swatchOption['value']) ?> no-repeat center; background-size: initial;">
                            </div>
                            <?php break;
                        case '0':
                        default:
                            ?>
                            <div class="swatch-option text <?= $block->escapeHtmlAttr($label['custom_style']) ?>"
                                option-type="0"
                                data-option-type="0"
                                option-id="<?= $block->escapeHtmlAttr($option) ?>"
                                data-option-id="<?= $block->escapeHtmlAttr($option) ?>"
                                option-label="<?= $block->escapeHtmlAttr($label['label']) ?>"
                                data-option-label="<?= $block->escapeHtmlAttr($label['label']) ?>"
                                option-tooltip-thumb=""
                                data-option-tooltip-thumb=""
                                option-tooltip-value=""
                                data-option-tooltip-value=""
                            >
                                <?= $block->escapeHtml($swatchOption['value']) ?>
                            </div>
                        <?php break;
                    } ?>
                <?php endif; ?>
            </a>
        <?php endforeach; ?>
    </div>
</div>

<?php if ($viewModel->canShowSwatchTooltip()):?>
    <script>
        require(["jquery", "Magento_Swatches/js/swatch-renderer"], function ($) {
            $('.swatch-layered.<?= /* @escapeNotVerified */ $swatchData['attribute_code'] ?>')
                .find('[option-type="1"], [option-type="2"], [option-type="0"], [option-type="3"]')
                .SwatchRendererTooltip();
        });
    </script>
<?php endif;?>
