<?php
/**
 * Template has been overwritten in order to:
 * 1. Add additional container (label) for filter title and count (lines: 22, 34)
 * 2. All echoes changed into shorthand
 * 3. Helper for displaying count assigned to variable
 * 4. Improve a11y
 * 5. Add support for masked categories
 * Aligned with theme-cs v21 in 07/2025
 *
 * @var $block \Smile\ElasticsuiteCatalog\Block\Navigation\FilterRenderer
 * @var $escaper \Magento\Framework\Escaper
 * @var $viewModel \Creativestyle\CustomizationIpetCatalog\ViewModel\SeoLinkMasking\Category
 * @var $filterItems \Smile\ElasticsuiteCatalog\Model\Layer\Filter\Item\Category[]
 */

$viewModel = $block->getViewModel();
$displayProductCountOnLayer = $this->helper(\Magento\Catalog\Helper\Data::class)->shouldDisplayProductCountOnLayer(); //phpcs:ignore
?>

<ol class="items">
    <?php foreach ($filterItems as $key=>$filterItem): ?>
        <li class="item">
            <?php if ($filterItem->getCount() > 0): ?>
                <a <?= /* @noEscape */ $viewModel->getCategoryFilterUrl($filterItem); ?>>
                    <?php if ($this->isMultipleSelectEnabled()) : ?>
                        <input id="<?= $escaper->escapeHtmlAttr($filterItem->getLabel() . '_' . $key) ?>" type="checkbox" onclick="this.parentNode.click();" <?php if($filterItem->getIsSelected()) : ?>checked<?php endif; ?> />
                        <label for="<?= $escaper->escapeHtmlAttr($filterItem->getLabel() . '_' . $key) ?>">
                    <?php else: ?>
                        <span>
                    <?php endif; ?>
                        <?= /* @escapeNotVerified */ $filterItem->getLabel() ?>
                        <?php if ($displayProductCountOnLayer): ?>
                            <span class="count">
                                <?= /* @escapeNotVerified */ $filterItem->getCount()?>
                            <span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1):?>
                                <?= /* @escapeNotVerified */ __('item')?>
                            <?php else:?>
                                <?= /* @escapeNotVerified */ __('items') ?>
                            <?php endif;?></span></span>
                        <?php endif; ?>
                    </<?= $this->isMultipleSelectEnabled() ? 'label' : 'span' ?>>
                </a>
            <?php else:?>
                <?= /* @escapeNotVerified */ $filterItem->getLabel() ?>
                <?php if ($displayProductCountOnLayer): ?>
                    <span class="count">
                        <?= /* @escapeNotVerified */ $filterItem->getCount()?>
                        <span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1):?>
                            <?= /* @escapeNotVerified */ __('item')?>
                        <?php else:?>
                            <?= /* @escapeNotVerified */ __('items') ?><?php endif;?>
                        </span>
                    </span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>
