<?php
/**
 * Template has been overwritten in order to:
 * 1. Add additional container (label) for filter title and count (lines: 22, 34)
 * 2. All echoes changed into shorthand
 * 3. Helper for displaying count assigned to variable
 * 4. Add support for masked categories
 *
 * @var $block \Smile\ElasticsuiteCatalog\Block\Navigation\FilterRenderer
 * @var $viewModel \Creativestyle\CustomizationIpetCatalog\ViewModel\SeoLinkMasking\Category
 * @var $filterItems \Smile\ElasticsuiteCatalog\Model\Layer\Filter\Item\Category[]
 */

$viewModel = $block->getViewModel();
$displayProductCountOnLayer = $this->helper(\Magento\Catalog\Helper\Data::class)->shouldDisplayProductCountOnLayer(); //phpcs:ignore
?>

<ol class="items">
    <?php foreach ($filterItems as $filterItem) : ?>
        <li class="item">
            <?php if ($filterItem->getCount() > 0) : ?>
                <a <?= /* @noEscape */ $viewModel->getCategoryFilterUrl($filterItem); ?>>
                    <?php if ($block->isMultipleSelectEnabled()) : ?>
                        <input type="checkbox" onclick="this.parentNode.click();" <?php if ($filterItem->getIsSelected()) : ?>checked<?php endif; ?> />
                    <?php endif; ?>
                    <label>
                        <?= /* @noEscape */ $filterItem->getLabel() ?>
                        <?php if ($displayProductCountOnLayer) : ?>
                            <span class="count">
                                <?= /* @noEscape */ $filterItem->getCount() ?>
                            <span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1) : ?>
                                <?= /* @noEscape */ __('item') ?>
                            <?php else : ?>
                                <?= /* @noEscape */ __('items') ?>
                            <?php endif; ?></span></span>
                        <?php endif; ?>
                    </label>
                </a>
            <?php else : ?>
                <?= /* @noEscape */ $filterItem->getLabel() ?>
                <?php if ($displayProductCountOnLayer) : ?>
                    <span class="count">
                        <?= /* @noEscape */ $filterItem->getCount() ?>
                        <span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1) : ?>
                            <?= /* @noEscape */ __('item') ?>
                        <?php else : ?>
                            <?= /* @noEscape */ __('items') ?><?php endif;?>
                        </span>
                    </span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>
